site_name: Zhymabek Roman's blog site
site_description: "My thoughts, projects and etc."
repo_url: "https://github.com/ZhymabekRoman/zhymabekroman.github.io"
repo_name: "ZhymabekRoman.github.io"

nav:
  - Home: index.md
  - Posts:
    - 2023:
      - posts/must-have-applications.md
      - posts/must-have-browser-extensions.md
      - posts/custom-telegram-client-api-credits.md
      - posts/transcribe-trial-reset.md
    - 2024:
      - posts/whatsapp-api.md
  - About: about.md

theme:
  name: 'material'
  custom_dir: docs/templates
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - scheme: slate
    primary: black
    accent: violet
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: default
    primary: violet
    accent: black
    toggle:
      icon: material/weather-night
      name: Switch to system preference

plugins:
  - redirects:
      redirect_maps:
        'about.md': 'https://github.com/ZhymabekRoman'

extra_css:
- css/custom.css

extra_javascript:
- javascripts/yandex_metrika.js
