name: Page deploy
on:
  push:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: |
            .cache
            poetry.lock
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Deploy MkDocs
        run: poetry run mkdocs gh-deploy --force
